// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['service']['TodoService']['AddTodo'](arg1);
}

export function ClearAll() {
  return window['go']['service']['TodoService']['ClearAll']();
}

export function GetTodos() {
  return window['go']['service']['TodoService']['GetTodos']();
}

export function RemoveTodo(arg1) {
  return window['go']['service']['TodoService']['RemoveTodo'](arg1);
}
