// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AddTodo(arg1:string):Promise<void>;

export function ClearAll():Promise<void>;

export function GetTodos():Promise<Array<db.Todo>>;

export function RemoveTodo(arg1:string):Promise<void>;
